apiVersion: skaffold/v2beta2
kind: Config

build:
  artifacts:
    - image: service-a-nodejs-think2020
      context: service-a
    - image: service-b-nodejs-think2020
      context: service-b

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: service-a-nodejs-think2020
          context: service-a
          docker:
            buildArgs:
              ENV: development
          sync:
            infer:
              - "src/**/*.js"
        - image: service-b-nodejs-think2020
          context: service-b
          docker:
            buildArgs:
              ENV: development
          sync:
            infer:
              - "src/**/*.js"


