apiVersion: skaffold/v2beta15
kind: Config

build:
  artifacts:
    - image: nodejs-k8s-think2020
      context: ../1-containers
      
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: nodejs-k8s-think2020
          context: ../1-containers
          docker:
            buildArgs:
              ENV: development
          sync:
            infer:
              - "server/**/*.js"


