apiVersion: skaffold/v2beta2
kind: Config

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}"
      artifacts:
        - image: csantanapr/nodejs-k8s-think2020
          context: ../1-containers
          docker:
            buildArgs:
              ENV: development
          sync:
            infer:
              - "server/**/*.js"

build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}"
  artifacts:
    - image: csantanapr/nodejs-k8s-think2020
      context: ../1-containers
